---
title: "Oyster hemolymph OA trial"
author: "Samuel Gurr"
date: "3/30/2022"
output:
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
---


```{r setup, include=FALSE}

# LOAD PACKAGES :::::::::::::::::::::::::::::::::::::::::::::::::::::::

library(dplyr)
library(ggplot2)
library(lme4)
library(lmerTest)
library(performance)
library(kableExtra)
library(pander)
library(ggpubr)

# SET WORKING DIRECTORY :::::::::::::::::::::::::::::::::::::::::::::::

 setwd("C:/Users/samuel.gurr/Documents/Github_repositories/Cvirginica_hemolymph_OA/RAnalysis/") # personal computer
# setwd("C:/Users/samjg/Documents/Github_repositories/Airradians_multigen_OA/RAnalysis") # Work computer

# LOAD DATA :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
MitPotential_dat    <- read.csv(file="Flow_cytometry_data/Output/JC10_results.csv", header=T)

ROS_dat             <- read.csv(file="Flow_cytometry_data/Output/DCFHDA_results.csv", header=T)

```




```{r Analysis - Mitochondrial Potential, echo=FALSE}

# add column for pCO2 treatment
MitPotential_dat <- MitPotential_dat %>% 
      dplyr::mutate(pCO2 = case_when(pCO2_Treatment == "Low"  ~ "500 μatm", pCO2_Treatment == "High" ~ "1200 μatm")) %>% # add a column for pCO2
      dplyr::mutate(Ratio_FL1.FL2 = as.numeric(Ratio_FL1.FL2))  %>% 
      dplyr::mutate(pCO2_Treatment = as.factor(pCO2_Treatment))

# parse by cell type for stats
MitPotential_MG     <- MitPotential_dat %>% dplyr::filter(cell_type %in% 'mature_granular')   %>% na.omit()
MitPotential_IG     <- MitPotential_dat %>% dplyr::filter(cell_type %in% 'immature_granular') %>% na.omit()
MitPotential_MA     <- MitPotential_dat %>% dplyr::filter(cell_type %in% 'mature_agranular')  %>% na.omit()
MitPotential_Degran <- MitPotential_dat %>% dplyr::filter(cell_type %in% 'degranulated')      %>% na.omit()



# view means :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



MitPotential_dat %>% 
      na.omit() %>%  
      summarySE(measurevar="Ratio_FL1.FL2", groupvars=c("pCO2_Treatment", "cell_type")) %>% 
      dplyr::mutate(pCO2 = case_when(pCO2_Treatment == "Low"  ~ "500 μatm", pCO2_Treatment == "High" ~ "1200 μatm")) %>% 
      dplyr::arrange(cell_type)



# ANOVA ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# model - TWO way anova pCO2 * cell type ::::::::::::::::::::::::::::::::::

MitPot_TwoWayANOVA <- lm(Ratio_FL1.FL2~pCO2_Treatment*cell_type, data = MitPotential_dat)
pander(anova(MitPot_TwoWayANOVA), style='rmarkdown') # anova table of lmer
# |            &nbsp;            | Df | Sum Sq  | Mean Sq | F value |  Pr(>F)   |
# |:----------------------------:|:--:|:-------:|:-------:|:-------:|:---------:|
# |      **pCO2_Treatment**      | 1  | 0.07293 | 0.07293 |  1.012  |  0.3212   |
# |        **cell_type**         | 3  |  6.862  |  2.287  |  31.73  | 3.267e-10 |
# | **pCO2_Treatment:cell_type** | 3  | 0.04299 | 0.01433 | 0.1988  |  0.8965   |
# |        **Residuals**         | 36 |  2.595  | 0.07208 |   NA    |    NA     |
shapiro.test(residuals(MitPot_TwoWayANOVA)) # normality of model residuals:  0.2058
leveneTest(MitPot_TwoWayANOVA) # heteroscedasticity (absence of homoscedasticity): 0.818


# model - mature granular  ::::::::::::::::::::::::::::::::::

MitPot_MG_ANOVA <- lm(Ratio_FL1.FL2~pCO2_Treatment, data = MitPotential_MG)
pander(anova(MitPot_MG_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df | Sum Sq  | Mean Sq | F value | Pr(>F) |
# |:------------------:|:--:|:-------:|:-------:|:-------:|:------:|
# | **pCO2_Treatment** | 1  | 0.04441 | 0.04441 | 0.6667  | 0.4353 |
# |   **Residuals**    | 9  | 0.5995  | 0.06662 |   NA    |   NA   |
shapiro.test(residuals(MitPot_MG_ANOVA)) # normality of model residuals:  0.7315
leveneTest(MitPot_MG_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.675


# model - immature granular  ::::::::::::::::::::::::::::::::::

MitPot_IG_ANOVA <- lm(Ratio_FL1.FL2~pCO2_Treatment, data = MitPotential_IG)
pander(anova(MitPot_IG_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df | Sum Sq  | Mean Sq | F value | Pr(>F) |
# |:------------------:|:--:|:-------:|:-------:|:-------:|:------:|
# | **pCO2_Treatment** | 1  | 0.06599 | 0.06599 | 0.4704  | 0.5101 |
# |   **Residuals**    | 9  |  1.263  | 0.1403  |   NA    |   NA   |
shapiro.test(residuals(MitPot_IG_ANOVA)) # normality of model residuals:  0.5247
leveneTest(MitPot_IG_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.8426


# model - mature agranular  ::::::::::::::::::::::::::::::::::

MitPot_MA_ANOVA <- lm(Ratio_FL1.FL2~pCO2_Treatment, data = MitPotential_MA)
pander(anova(MitPot_MA_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df |  Sum Sq   |  Mean Sq  |  F value  | Pr(>F) |
# |:------------------:|:--:|:---------:|:---------:|:---------:|:------:|
# | **pCO2_Treatment** | 1  | 3.117e-06 | 3.117e-06 | 5.874e-05 | 0.9941 |
# |   **Residuals**    | 9  |  0.4775   |  0.05306  |    NA     |   NA   |
shapiro.test(residuals(MitPot_MA_ANOVA)) # normality of model residuals:  0.07573
leveneTest(MitPot_MA_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.8953


# model - degranulated ::::::::::::::::::::::::::::::::::

MitPot_Degran_ANOVA <- lm(Ratio_FL1.FL2~pCO2_Treatment, data = MitPotential_Degran)
pander(anova(MitPot_Degran_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df | Sum Sq  | Mean Sq | F value | Pr(>F) |
# |:------------------:|:--:|:-------:|:-------:|:-------:|:------:|
# | **pCO2_Treatment** | 1  | 0.00551 | 0.00551 | 0.1945  | 0.6696 |
# |   **Residuals**    | 9  |  0.255  | 0.02833 |   NA    |   NA   |
shapiro.test(residuals(MitPot_Degran_ANOVA)) # normality of model residuals:  0.7314
leveneTest(MitPot_Degran_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.4407




# plot :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



MitPotenital_PLOT <- ggplot(MitPotential_dat, aes(x = factor(pCO2, level = c('500 μatm', '1200 μatm')), Ratio_FL1.FL2 , fill = pCO2)) +
                          theme(panel.grid=element_blank()) +
                          geom_boxplot(size=0.2, width=0.5, alpha=0.1, aes(fill=pCO2)) +
                          scale_fill_manual(values=c("grey20","white")) +
                          geom_point(shape = 21, size = 2, position = position_jitterdodge(jitter.width = 0.1)) +
                          theme_classic() +
                          scale_x_discrete(labels= c('~500 μatm', '~1200 μatm')) +
                         # scale_y_continuous(expand = c(0, 0), limits = c(0, 2)) +
                          labs(title = "Cvirginica - Mitchondrial potenital under OA", 
                               y = expression(Arbitrary~units~"("~A~U~")"),
                               x = expression(italic(p)*CO[2]~Treatment~"("~μ*atm~")")) + 
                          theme(axis.text=element_text(size=8),
                                axis.title=element_text(size=8,face="bold")) +
                          stat_summary(fun.y=mean, geom="point", shape=18, size=4, color="black", fill="white") +
                          facet_wrap(~cell_type, scales = "free")  
MitPotenital_PLOT # print this figure...


# Export the figures to pdf
ggarrange(MitPotenital_PLOT,ROS_PLOT,nrow = 2) %>%
  ggexport(filename = "C:/Users/samuel.gurr/Documents/Github_repositories/Cvirginica_hemolymph_OA/RAnalysis/Flow_cytometry_data/Output/MitochondrialPotential_ROS.pdf")

```




```{r Analysis - Mitochondrial Potential, echo=FALSE}

# add column for pCO2 treatment
ROS_dat <- ROS_dat %>% 
      dplyr::mutate(pCO2 = case_when(pCO2_Treatment == "Low"  ~ "500 μatm", pCO2_Treatment == "High" ~ "1200 μatm")) %>% # add a column for pCO2
      dplyr::mutate(Mean_FL1 = as.numeric(Mean_FL1))  %>% 
      dplyr::mutate(pCO2_Treatment = as.factor(pCO2_Treatment))

# parse by cell type for stats
ROS_MG     <- ROS_dat %>% dplyr::filter(cell_type %in% 'mature_granular')   %>% na.omit()
ROS_IG     <- ROS_dat %>% dplyr::filter(cell_type %in% 'immature_granular') %>% na.omit()
ROS_MA     <- ROS_dat %>% dplyr::filter(cell_type %in% 'mature_agranular')  %>% na.omit()
ROS_Degran <- ROS_dat %>% dplyr::filter(cell_type %in% 'degranulated')      %>% na.omit()



# view means :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



ROS_dat %>% 
      na.omit() %>%  
      summarySE(measurevar="Mean_FL1", groupvars=c("pCO2_Treatment", "cell_type")) %>% 
      dplyr::mutate(pCO2 = case_when(pCO2_Treatment == "Low"  ~ "500 μatm", pCO2_Treatment == "High" ~ "1200 μatm")) %>% 
      dplyr::arrange(cell_type)



# ANOVA ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



# model - TWO way anova pCO2 * cell type ::::::::::::::::::::::::::::::::::

ROS_TwoWayANOVA <- lm(Mean_FL1~pCO2_Treatment*cell_type, data = ROS_dat)
pander(anova(ROS_TwoWayANOVA), style='rmarkdown') # anova table of lmer
# |            &nbsp;            |  Pr(>F)   |
# |:----------------------------:|:---------:|
# |      **pCO2_Treatment**      |  0.1214   |
# |        **cell_type**         | 1.457e-07 |
# | **pCO2_Treatment:cell_type** |  0.5075   |
# |        **Residuals**         |    NA     |
shapiro.test(residuals(ROS_TwoWayANOVA)) # normality of model residuals:  0.0004203
leveneTest(ROS_TwoWayANOVA) # heteroscedasticity (absence of homoscedasticity): 0.0006359 


# model - mature granular  ::::::::::::::::::::::::::::::::::

ROS_MG_ANOVA <- lm(Mean_FL1~pCO2_Treatment, data = ROS_MG)
pander(anova(ROS_MG_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df |  Sum Sq   |  Mean Sq  | F value | Pr(>F) |
# |:------------------:|:--:|:---------:|:---------:|:-------:|:------:|
# | **pCO2_Treatment** | 1  | 6.907e+10 | 6.907e+10 |  1.393  | 0.2681 |
# |   **Residuals**    | 9  | 4.462e+11 | 4.958e+10 |   NA    |   NA   |
shapiro.test(residuals(ROS_MG_ANOVA)) # normality of model residuals:  0.8843
leveneTest(ROS_MG_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.07918 


# model - immature granular  ::::::::::::::::::::::::::::::::::

ROS_IG_ANOVA <- lm(Mean_FL1~pCO2_Treatment, data = ROS_IG)
pander(anova(ROS_IG_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df |  Sum Sq   |  Mean Sq  | F value | Pr(>F) |
# |:------------------:|:--:|:---------:|:---------:|:-------:|:------:|
# | **pCO2_Treatment** | 1  | 1.233e+09 | 1.233e+09 | 0.5332  | 0.4838 |
# |   **Residuals**    | 9  | 2.081e+10 | 2.312e+09 |   NA    |   NA   |
shapiro.test(residuals(ROS_IG_ANOVA)) # normality of model residuals:  0.5247
leveneTest(ROS_IG_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.8426


# model - mature agranular  ::::::::::::::::::::::::::::::::::

ROS_MA_ANOVA <- lm(Mean_FL1~pCO2_Treatment, data = ROS_MA)
pander(anova(ROS_MA_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df |  Sum Sq   |  Mean Sq  | F value | Pr(>F) |
# |:------------------:|:--:|:---------:|:---------:|:-------:|:------:|
# | **pCO2_Treatment** | 1  | 677074538 | 677074538 | 0.4297  | 0.5285 |
# |   **Residuals**    | 9  | 1.418e+10 | 1.576e+09 |   NA    |   NA   |
shapiro.test(residuals(ROS_MA_ANOVA)) # normality of model residuals:  0.07573
leveneTest(ROS_MA_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.8953


# model - degranulated ::::::::::::::::::::::::::::::::::

ROS_Degran_ANOVA <- lm(Mean_FL1~pCO2_Treatment, data = ROS_Degran)
pander(anova(ROS_Degran_ANOVA), style='rmarkdown') # anova table of lmer
# |       &nbsp;       | Df |  Sum Sq   |  Mean Sq  | F value | Pr(>F) |
# |:------------------:|:--:|:---------:|:---------:|:-------:|:------:|
# | **pCO2_Treatment** | 1  | 5.222e+09 | 5.222e+09 | 0.5857  | 0.4637 |
# |   **Residuals**    | 9  | 8.023e+10 | 8.914e+09 |   NA    |   NA   |
shapiro.test(residuals(ROS_Degran_ANOVA)) # normality of model residuals:  0.711
leveneTest(ROS_Degran_ANOVA) # heteroscedasticity (absence of homoscedasticity): 0.1054




# plot :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::



ROS_PLOT <- ggplot(ROS_dat, aes(x = factor(pCO2, level = c('500 μatm', '1200 μatm')), Mean_FL1 , fill = pCO2)) +
                          theme(panel.grid=element_blank()) +
                          geom_boxplot(size=0.2, width=0.5, alpha=0.1, aes(fill=pCO2)) +
                          scale_fill_manual(values=c("grey20","white")) +
                          geom_point(shape = 21, size = 2, position = position_jitterdodge(jitter.width = 0.1)) +
                          theme_classic() +
                          scale_x_discrete(labels= c('~500 μatm', '~1200 μatm')) +
                         # scale_y_continuous(expand = c(0, 0), limits = c(0, 2)) +
                          labs(title = "Cvirginica - ROS under OA", 
                               y = expression(Arbitrary~units~"("~A~U~")"),
                               x = expression(italic(p)*CO[2]~Treatment~"("~μ*atm~")")) + 
                          theme(axis.text=element_text(size=8),
                                axis.title=element_text(size=8,face="bold")) +
                          stat_summary(fun.y=mean, geom="point", shape=18, size=4, color="black", fill="white") +
                          facet_wrap(~cell_type, scales = "free")  
ROS_PLOT # print this figure...



```

